### PR TITLE
JGs pull request

### PR DESCRIPTION
**Pull request by jgeulaGA**
text text text

### CODE REVIEW

**Comment by jschneier** [comment]
Hey can you create a directory (folder) with your name or some abbreviation of it as the directory name? That's where you'll be submitting all your assignment, otherwise it's way too easy for you to clash with other students, image you all try to edit the same file. There are some examples of other students who have done so already in the repository that you already forked.

If you update your branch on your computer when you do ``git push origin master`` it should update this pull request automatically (it matches up the branches). Just as a reminder, to remove a file you need to use ``git rm``, not just ``rm``.

**Comment by Aerlinger** [comment]
Hey @jgeulaGA, wanted to ping you on this. Can you follow Josh's instructions above so we can get you fully setup?

Thanks,
  - Anthony

**Comment by jgeulaGA** [comment]
just gave it a shot @Aerlinger , let me know if it didn't work. thanks!

**Comment by jschneier** [comment]
@jgeulaGA that looks right, can you just ``git rm`` your 'test1.txt' that is outside of your folder and push up, i'll merge after that.

**Comment by jgeulaGA** [comment]
Cool, just made changes. All good?

**Comment by jschneier** [comment]
Great!

**Pull request merged**
