### PR TITLE
Assignments to date thru 4

### PR DESCRIPTION
**Pull request by EVCinNYC**
I've got this working with my own MashApe and Twitter APIs
What I wanted to do was to allow a user to put the input in using raw input
But I'm getting hung up on the fact that the term input (say @GA) needs to be put within quote marks
So when I do it in the function in line 70, it sort of chokes - 
  -- I've tried with quotes "%s" but then it just looks for %s tweets
  -- I've tried with /"%s/" but that doesn't seem to work either

Appreciate any thoughts there
Thanks, EVC

### CODE REVIEW

**Comment by jschneier** [comment]
Hey Eric. So ``raw_input`` returns a string by default. So ``begin_live_feed([term])`` should just work.

**Comment by EVCinNYC** [comment]
I wasn't sure if the read.md files will do the markup you requested - but hoping that worked
Will we review the in-class assignment, especially the apply and split functions?

**Comment by EVCinNYC** [comment]
Please see my notebook Assignment4_part2
I think I have started to groupby, but doing the basic plotting (date aggregation by count of casual or registered rides) through several attempts I'm getting errors and banging my head against the computer trying to resolve: 
* "cannot set an array element with a sequence"  << so I figure this is the date field and create a date field using pd.period_range() but then I get
* "x and y must have same first dimension"

I think this is straight forward but I'm really starting to doubt my ability to troubleshoot this

**Comment by Aerlinger** [comment]
@EVCinNYC This looks great thanks. Unfortunately, we didn't have time to cover Split, Apply, Combine. We'll cover it a bit when we talk about distributed computing, but happy to answer any questions you have on it directly.

**Pull request merged**
