### PR TITLE
test

### PR DESCRIPTION
**Pull request by blueocean5612**

### CODE REVIEW

**Comment by jschneier** [comment]
That's where you'll be submitting all your assignment, otherwise it's way too easy for you to clash with other students, image you all try to edit the same file. There are some examples of other students who have done so already in the repository that you already forked.

If you update your branch on your computer when you do ``git push origin master`` it should update this pull request automatically (it matches up the branches). Just as a reminder, to remove a file you need to use ``git rm``, not just ``rm``.

**Comment by Aerlinger** [comment]
Hey @blueocean5612, wanted to ping you on this. Can you follow Josh's instructions above so we can get you fully setup?

Thanks,
  - Anthony

**Comment by blueocean5612** [comment]
Is it better?

**Comment by Aerlinger** [comment]
@blueocean5612 See how there are four commits in the history of this PR? Two of them (ids `1f8122c5a03ae2cfb8c1520ab98126d6f6542096` and `7a2e1a3055b44813ceca04e121a0cd892d12e0da`) make changes outside of your 'vince' folder. You can use `git revert <ID>` on both of those commits to revert those changes, then submit another PR. You'll know it's OK if this page says "This pull request can be automatically merged." with a green icon.

**Comment by blueocean5612** [comment]
well, revert didn't work "error: 'revert' is not possible because you have unmerged files.", so I've reset it completely. It seems ok now,... Phew.

**Comment by Aerlinger** [comment]
Looks better, can you add a Readme to your repository in markdown as well?

**Comment by Aerlinger** [comment]
@jschneier I'll leave it up to you to merge.

**Pull request merged**
